"""
game_engine.py
--------------
Game loop engine: countdown timers, server-side number calling, winner
validation and prize distribution.

Security model (Step 5 of the spec):
    1. number is generated by the SERVER
    2. number is saved to MongoDB (games.called_numbers)
    3. number is broadcast to every player in the game room
    4. players update their UI only

The frontend can never forge a win: `claim_bingo` re-validates the stored
card against the official called-numbers list via bingo_validator, and the
prize is computed and paid by the server.
"""
import random
import threading
import time

from backend.multiplayer.room_manager import Room
from backend.multiplayer.bingo_validator import check_bingo, get_completed_lines

CALL_INTERVAL = 3               # seconds between called numbers
COUNTDOWN_SECONDS = 35          # waiting countdown per game
READY_HOLD_SECONDS = 5        # GET READY screen duration before first call
MIN_PLAYERS = 2                 # game starts with at least 2 users
MIN_CARDS = 2                   # game starts with at least 2 cards total
                                # (2 distinct players must each hold a card)
PAYOUT_RATIO = 0.8              # 80% of the prize pool is distributed
SWEEPER_INTERVAL = 30           # room cleanup interval


class GameEngine:
    """
    One daemon thread per room drives the countdown + number calling.
    The thread exits when the room finishes; rooms are garbage-collected
    by the sweeper thread.
    """

    def __init__(self, manager, db=None, broadcast=None, broadcast_legacy=None):
        self.manager = manager
        self.db = manager.db if db is None else db
        self.broadcast = broadcast or (lambda gid, ev, data: None)
        self.broadcast_legacy = broadcast_legacy or (lambda gid, ev, data: None)
        self.purge_disconnected = None     # wired by SocketManager (refund+roster)
        self.loops = {}                    # game_id -> thread
        self._loop_lock = threading.Lock()
        self._started = False

    def _purge(self, game_id):
        """Drop offline ghosts; keep the lobby count honest."""
        try:
            if self.purge_disconnected:
                self.purge_disconnected(game_id)
        except Exception as e:
            print(f"[game_engine] purge error for {game_id}: {e}")

    # ------------------------------------------------------------- lifecycle
    def start(self):
        """Start the background sweeper (safe to call once)."""
        if self._started:
            return
        self._started = True
        threading.Thread(target=self._sweeper, daemon=True).start()

    def _sweeper(self):
        while True:
            time.sleep(SWEEPER_INTERVAL)
            try:
                self.manager.cleanup_rooms()
            except Exception as e:
                print(f"[game_engine] sweeper error: {e}")

    def ensure_loop(self, game_id):
        """Spawn the room loop thread for a game (idempotent)."""
        with self._loop_lock:
            t = self.loops.get(game_id)
            if t and t.is_alive():
                return
            room = self.manager.get_room(game_id)
            if not room:
                return
            if room.deadline is None:
                room.deadline = time.time() + COUNTDOWN_SECONDS
            t = threading.Thread(target=self._room_loop, args=(game_id,), daemon=True)
            self.loops[game_id] = t
            t.start()

    def extend_on_join(self, room):
        """DEPRECATED: never extend the countdown (timer must run straight)."""
        return

    # ---------------------------------------------------------- room thread
    def _room_loop(self, game_id):
        room = self.manager.get_room(game_id)
        if not room:
            return
        no_card_streak = 0
        try:
            # ---------- WAITING phase: broadcast countdown every second.
            # The countdown NEVER resets while players are joining or picking
            # cards. When it expires without enough cards, the SAME game (same
            # game_id) simply re-counts: nothing is cancelled, nothing is
            # deleted, no refunds, no "game cancelled" messages. Players keep
            # their cards and wait for more users to join this same game.
            last_tick = 0.0
            while room.status == Room.WAITING:
                now = time.time()
                if now - last_tick >= 1.0:
                    last_tick = now
                    self._purge(game_id)
                    self.broadcast(game_id, 'timer_update', {
                        'game_id': game_id,
                        'time_left': room.time_left(),
                        'status': Room.WAITING,
                    })
                if room.online_count() == 0:
                    # Nobody connected in the lobby: stop broadcasting a
                    # countdown so the game does not appear to open by itself.
                    # The room stays open for this stake; the next joiner
                    # restarts the countdown via ensure_loop, and the sweeper
                    # reclaims the room if nobody ever returns.
                    break
                if room.deadline and time.time() >= room.deadline:
                    if room.online_count() < MIN_PLAYERS or room.playing_count() < MIN_PLAYERS:
                        # fewer than 2 CONNECTED users OR fewer than 2 users
                        # holding cards -> keep the SAME game id and restart
                        # the countdown. One user with two cards does NOT
                        # count: two distinct players must hold cards.
                        # Disconnected ghosts do NOT count. Never cancel.
                        room.deadline = time.time() + COUNTDOWN_SECONDS
                        continue
                    self.start_game(room)
                    break
                time.sleep(0.1)

            # ---------- GET READY gate: hold ALL balls for READY_HOLD_SECONDS,
            # then the game starts automatically - no button, no click.
            ready_deadline = time.time() + READY_HOLD_SECONDS
            while room.status == Room.RUNNING and time.time() < ready_deadline:
                self.broadcast(game_id, 'ready_update', {
                    'game_id': game_id,
                    'ready_until': ready_deadline,
                })
                time.sleep(0.25)
            with room.lock:
                room.ready_phase = False

            # ---------- RUNNING phase: call a number every CALL_INTERVAL
            first_ball = True     # first ball fires immediately after GET READY
            next_call = time.time()
            while room.status == Room.RUNNING:
                if room.paused:
                    time.sleep(1)
                    continue
                if room.player_count() == 0:
                    # everybody left -> do not keep calling balls for a ghost
                    # game. Finish right away (0 cards -> 0 prize, no payouts).
                    self.finish_game(room, 'no_players')
                    break
                if len(room.winners) >= room.max_winners:
                    self.finish_game(room, 'winners_reached')
                    break
                if len(room.called) >= 75:
                    self.finish_game(room, 'no_more_balls')
                    break
                if not first_ball:
                    # absolute pacing: wait until next_call (never bursts even
                    # if this thread was delayed by DB/socket work)
                    while time.time() < next_call:
                        if room.status != Room.RUNNING:
                            break
                        time.sleep(0.05)
                    if room.status != Room.RUNNING:
                        break
                    if room.paused:
                        continue
                first_ball = False
                self._purge(game_id)
                self.call_number(room)
                next_call = time.time() + CALL_INTERVAL
                if len(room.winners) >= room.max_winners:
                    self.finish_game(room, 'winners_reached')
                    break
                if len(room.called) >= 75:
                    self.finish_game(room, 'no_more_balls')
                    break
        except Exception as e:
            print(f"[game_engine] loop error for {game_id}: {e}")

    def start_game(self, room):
        """Transition a room from waiting to running."""
        with room.lock:
            if room.status != Room.WAITING:
                return
            room.status = Room.RUNNING
            room.started_at = time.time()
            room.deadline = None
            # GET READY gate: no ball may be called until every card-holder
            # presses the GET READY button (or the ready timeout expires).
            room.ready_phase = True
            room.ready_players = set()
            try:
                self.db.update_game_record(
                    room.game_id,
                    status=Room.RUNNING,
                    started_at=time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(room.started_at)),
                    players_count=room.player_count(),
                    prize_pool=room.prize_pool(),
                )
            except Exception as e:
                print(f"[game_engine] db update_game_record(start) error: {e}")
        self.manager.reset_open(room)
        payload = {
            'game_id': room.game_id,
            'stake': room.stake,
            'players': room.total_cards(),
            'cards': room.total_cards(),
            'prize_pool': room.prize_pool(),
            'max_players': room.max_players,
            'max_winners': room.max_winners,
            'ready': True,
        }
        self.broadcast(room.game_id, 'game_started', payload)
        self.broadcast_legacy(room.game_id, 'game_started', {
            'room': room.stake,
            'game_id': room.game_id,
            'total_players': room.total_cards(),
        })

    def call_number(self, room):
        """Server picks the next unique number, saves it, then broadcasts."""
        with room.lock:
            if room.status != Room.RUNNING:
                return
            available = [n for n in range(1, 76) if n not in room.called]
            if not available:
                return
            number = random.choice(available)
            room.called.append(number)
            room.current_number = number
            # auto-mark every card: only the cell whose COLUMN matches the call
            # (B-13 marks ONLY the 13 inside the B column, never another column)
            call_col = (number - 1) // 15
            for p in room.players.values():
                for c in p.cards:
                    for idx, v in enumerate(c['numbers']):
                        if v == number and idx % 5 == call_col:
                            c['marked'].add(idx)
            try:
                # STEP 5: generate -> save to DB -> broadcast
                self.db.update_game_record(
                    room.game_id,
                    called_numbers=list(room.called),
                    current_number=number,
                )
            except Exception as e:
                print(f"[game_engine] db update_game_record(call) error: {e}")
        payload = {
            'game_id': room.game_id,
            'number': number,
            'called_count': len(room.called),
            'current_number': number,
        }
        self.broadcast(room.game_id, 'number_called', payload)
        self.broadcast_legacy(room.game_id, 'ball_called', {
            'room': room.stake,
            'number': number,
        })

    def call_specific(self, game_id, number, manual=True):
        """Admin manual call: inject a specific number into a running game."""
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        if not isinstance(number, int) or number < 1 or number > 75:
            return {'ok': False, 'error': 'invalid_number'}
        with room.lock:
            if room.status != Room.RUNNING:
                return {'ok': False, 'error': 'game_not_running'}
            if number in room.called:
                return {'ok': False, 'error': 'already_called'}
            room.called.append(number)
            room.current_number = number
            call_col = (number - 1) // 15
            for p in room.players.values():
                for c in p.cards:
                    for idx, v in enumerate(c['numbers']):
                        if v == number and idx % 5 == call_col:
                            c['marked'].add(idx)
            try:
                self.db.update_game_record(room.game_id, called_numbers=list(room.called), current_number=number)
            except Exception as e:
                print(f"[game_engine] db update_game_record(manual) error: {e}")
        payload = {'game_id': game_id, 'number': number,
                   'called_count': len(room.called), 'current_number': number}
        self.broadcast(game_id, 'number_called', payload)
        self.broadcast_legacy(game_id, 'ball_called', {
            'room': room.stake, 'number': number, 'manual': manual})
        return {'ok': True, 'number': number}

    def start_now(self, game_id):
        """Admin: skip the countdown and start immediately."""
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        room.deadline = time.time() - 0.01      # loop will start on next tick
        return {'ok': True}

    def set_max_winners(self, game_id, max_winners):
        """Admin: how many winners a game may have (1..4)."""
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        room.max_winners = max(1, min(4, int(max_winners)))
        self.broadcast_legacy(game_id, 'max_winners_updated', {
            'room': room.stake, 'max': room.max_winners})
        return {'ok': True, 'max_winners': room.max_winners}

    def pause_resume(self, game_id):
        """Admin: toggle pause on a running game."""
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        room.paused = not room.paused
        self.broadcast_legacy(game_id, 'game_paused', {
            'room': room.stake, 'paused': room.paused})
        return {'ok': True, 'paused': room.paused}

    # ------------------------------------------------------------ claiming
    def claim_bingo(self, game_id, user_id, card_id, name=None):
        """
        Validate a BINGO claim against the server-side called numbers.
        On success: record the winner, broadcast winner_found and finish
        the game when the max winner count is reached.
        """
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        with room.lock:
            if room.status != Room.RUNNING:
                return {'ok': False, 'error': 'game_not_running'}
            if len(room.winners) >= room.max_winners:
                return {'ok': False, 'error': 'game_already_won'}
            p = room.players.get(user_id)
            if not p:
                return {'ok': False, 'error': 'not_in_game'}
            card = next((c for c in p.cards if c['card_id'] == card_id), None)
            if not card:
                return {'ok': False, 'error': 'card_not_found'}
            called = set(room.called)
            completed = get_completed_lines(card['numbers'], called)
            if not completed:
                return {'ok': False, 'error': 'invalid_bingo'}
            if any(w['card_id'] == card_id for w in room.winners):
                return {'ok': False, 'error': 'already_claimed'}

            winner = {
                'user_id': user_id,
                'name': p.name or (name or 'Player'),
                'card_id': card_id,
                'card_label': card['label'],
                'lines': [list(l) for l in completed],
                'at': time.time(),
            }
            room.winners.append(winner)
            try:
                self.db.update_game_record(game_id, winner=user_id)
                self.db.update_card_marked(card_id, sorted(card['marked']))
            except Exception as e:
                print(f"[game_engine] db claim error: {e}")

            prize_pool = room.prize_pool()
            total_prize = int(prize_pool * PAYOUT_RATIO)
            per = int(total_prize / len(room.winners)) if total_prize else 0

            payload = {
                'game_id': game_id,
                'user_id': user_id,
                'winner_name': winner['name'],
                'card_id': card_id,
                'card_label': winner['card_label'],
                'prize_pool': prize_pool,
                'total_prize': total_prize,
                'prize_per_winner': per,
                'winners_count': len(room.winners),
                'max_winners': room.max_winners,
            }
            self.broadcast(game_id, 'winner_found', payload)
            self.broadcast_legacy(game_id, 'winner_found', {
                'room': room.stake,
                'user_id': user_id,
                'winner_name': winner['name'],
                'card_num': winner['card_label'],
                'card_index': 0,
                'prize': per,
                'total_players': room.total_cards(),
                'game_id': game_id,
            })

            # someone said BINGO with a real completed line - the game is over.
            # No more balls are called; pay out and show the winner screen now.
            self.finish_game(room, 'bingo')
            return {'ok': True, 'prize_per_winner': per, 'total_prize': total_prize}

    # -------------------------------------------------------------- finish
    def finish_game(self, room, reason):
        """
        End a running game: pay winners (main balance + transaction + game
        session), persist history and broadcast game_finished.
        """
        with room.lock:
            if room.status != Room.RUNNING:
                return
            room.status = Room.FINISHED
            room.finished_at = time.time()

            prize_pool = room.prize_pool()
            total_prize = int(prize_pool * PAYOUT_RATIO)
            winners_info = []
            if room.winners:
                per = int(total_prize / len(room.winners))
                for w in room.winners:
                    try:
                        self.db.update_main_balance(w['user_id'], per)
                        self.db.add_transaction(w['user_id'], 'bingo_win', per)
                        self.db.complete_game_session(w['user_id'], room.game_id, cards=w['card_id'], entry_amount=room.stake, result=f'+{per} Br', prize=per)
                        self.db.update_game_player_status(room.game_id, w['user_id'], 'won')
                    except Exception as e:
                        print(f"[game_engine] payout error for {w['user_id']}: {e}")
                    wcard = None
                    wp = room.players.get(w['user_id'])
                    if wp:
                        wcard = next((c for c in wp.cards if c['card_id'] == w['card_id']), None)
                    winners_info.append({
                        'user_id': w['user_id'],
                        'name': w['name'],
                        'card_id': w['card_id'],
                        'card_label': w['card_label'],
                        'prize': per,
                        'numbers': (wcard or {}).get('numbers') or [],
                        'marked': sorted((wcard or {}).get('marked') or []),
                        'lines': [list(l) for l in w.get('lines', [])],
                    })
                # persist final marked numbers and game sessions for every card
                # (the miniapp never calls /api/game_played, so sessions must be
                # created here or history / top winners stay empty)
                winner_ids = {w['user_id'] for w in room.winners}
                for p in room.players.values():
                    for c in p.cards:
                        try:
                            self.db.update_card_marked(c['card_id'], sorted(c['marked']))
                            if p.user_id in winner_ids:
                                self.db.complete_game_session(
                                    p.user_id, room.game_id, cards=c['card_id'],
                                    entry_amount=room.stake, result=f'+{per} Br', prize=per,
                                )
                            else:
                                self.db.complete_game_session(
                                    p.user_id, room.game_id, cards=c['card_id'],
                                    entry_amount=room.stake, result='-', prize=0,
                                )
                        except Exception as e:
                            print(f"[game_engine] persist marked error: {e}")

            try:
                self.db.update_game_record(
                    room.game_id,
                    status=Room.FINISHED,
                    finished_at=time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(room.finished_at)),
                    prize_pool=prize_pool,
                    winner=room.winners[0]['user_id'] if room.winners else None,
                )
                self.db.record_game_history(
                    room.game_id,
                    [p.name for p in room.players.values()],
                    [w['name'] for w in room.winners],
                    total_prize,
                    room.stake,
                )
            except Exception as e:
                print(f"[game_engine] db finish error: {e}")

            self.manager.reset_open(room)

            payload = {
                'game_id': room.game_id,
                'status': Room.FINISHED,
                'reason': reason,
                'winners': winners_info,
                'prize_pool': prize_pool,
                'total_prize': total_prize,
                'prize_per_winner': int(total_prize / len(room.winners)) if room.winners else 0,
                'stake': room.stake,
            }
            self.broadcast(room.game_id, 'game_finished', payload)
            self.broadcast_legacy(room.game_id, 'game_ended', {
                'room': room.stake,
                'game_id': room.game_id,
                'winners': winners_info,
                'prize': total_prize,
            })

    def cancel_game(self, game_id, reason='admin_cancelled'):
        """Cancel a game: refund every card stake to the players' wallets."""
        room = self.manager.get_room(game_id)
        if not room:
            return {'ok': False, 'error': 'room_not_found'}
        with room.lock:
            if room.status == Room.FINISHED or room.status == Room.CANCELLED:
                return {'ok': False, 'error': 'already_ended'}
            refund_total = 0
            for p in room.players.values():
                if p.cards:
                    amt = room.stake
                    try:
                        self.db.update_play_balance(p.user_id, amt)
                        self.db.add_transaction(p.user_id, 'bingo_refund', amt)
                        self.db.update_game_player_status(room.game_id, p.user_id, 'refunded')
                    except Exception as e:
                        print(f"[game_engine] refund error: {e}")
                    refund_total += amt
            room.status = Room.CANCELLED
            room.finished_at = time.time()
            try:
                self.db.update_game_record(game_id, status='cancelled')
            except Exception as e:
                print(f"[game_engine] db cancel error: {e}")
            self.manager.reset_open(room)
            self.broadcast(game_id, 'game_finished', {
                'game_id': game_id,
                'status': Room.CANCELLED,
                'reason': reason,
                'refund': refund_total,
                'winners': [],
            })
            self.broadcast_legacy(game_id, 'game_cancelled', {
                'room': room.stake,
                'reason': reason,
            })
            return {'ok': True, 'refund': refund_total}
